### ISSUE TITLE
Integrate dokka with hugo

### ISSUE THREAD

**Issue by hernandazevedozup** [ZupIT/beagle-docs#184]
https://github.com/cotechde/dokka-hugo-plugin

apply plugin: 'org.jetbrains.dokka'

    task dokkaHugo(type: org.jetbrains.dokka.gradle.DokkaTask) {
        dependencies {
            dokkaHugoPlugin 'com.github.cotechde:dokka-hugo-plugin:master-SNAPSHOT'
        }
    }

run the task by calling ./gradlew dokkaHugo

https://github.com/ZupIT/beagle/pull/1276

**Comment by carlossteinzup** [comment]
done
