### ISSUE TITLE
[WEB] Generate release notes in html, and link the new features to the doc page.

### ISSUE THREAD

**Issue by hernandazevedozup** [ZupIT/beagle-docs#208]
Generate a Release note like the image below in HTML so the features can be clicked and linked to the documentation for each one of the topics.

Suggestions:
Generate this HTML via script so can be done for all versions easily.

![release-note_01](https://user-images.githubusercontent.com/68112545/104025488-7b97d800-51a3-11eb-9a58-6a054b80e435.png)

**Comment by carlossteinzup** [comment]
done
