### ISSUE TITLE
There is a menu on the right side that is not accessible to the public

### ISSUE THREAD

**Issue by brunasilvazup** [ZupIT/beagle-docs#257]
## Use case

There is a menu on the right side that is not accessible to the public.

It's that menu ->
![image](https://user-images.githubusercontent.com/67295691/105884445-be9cdc80-5fe6-11eb-8062-a3a35052696c.png)

> ![image](https://user-images.githubusercontent.com/67295691/105884604-e2f8b900-5fe6-11eb-9fd8-312274ff5773.png)

In this case, the links are blocked for the public outside the zup, because this repo is private.

## Proposal

Perhaps it would be good to remove that part of the doc while the repository remains private.

**Comment by carlossteinzup** [comment]
Solved. Repo is now open and everyone could open an PR
