### ISSUE TITLE
Publicação de conteúdos sobre o beagle sobre assuntos específicos

### ISSUE THREAD

**Issue by hernandazevedozup** [ZupIT/beagle-docs#273]
Listar os conteudos a serem criados abaixo::

Mini Conteudos (Artigos)

https://docs.google.com/spreadsheets/d/1cpwl_0OCXuIJ3u8oOepTt5sjC_PxXWttv-f4EMUNFFw/edit?usp=sharing
- [x] Flex no Beagle
- [x] ListView
- [x] Custom Operations

Videos
- [x] Scaffold
- [x] Design System e Estilo
- [x] Custom Action
- [x] Custom Widget
- [x] Custom Operations
--

Exemplo de google docs de artigos:
https://docs.google.com/spreadsheets/d/13t5L68-AieZIcp51FUDcGxZaxRPpeHJEGvV7vo_jUqc/edit?usp=sharing

**Comment by carlossteinzup** [comment]
updated
