### ISSUE TITLE
Melhorar a usabilidade do search na doc

### ISSUE THREAD

**Issue by luismaximozup** [ZupIT/beagle-docs#433]
- [x] Busca por caracter inserido, ao invés de buscar por palavra ao apertar enter

- [x] Filtrar a pesquisa por lingua atual

**Comment by carlossteinzup** [comment]
"Galera tenho  algumas duvidas sobre a doc mais especificamente sobre a parte de busca o campo de texto que fica no canto superior a direita:
Existe a possibilidade de quando eu escrever mais de 3 caracteres ele ja realizar a busca para mim? atualmente é muito chato eu escrever e ter que dar enter.
Existe a possibilidade de filtrar pela lingua atual? eu acho meio estranho eu procurar por algo na lingua inglesa e a primeira indicação ser um link para pt-br"

**Comment by carlossteinzup** [comment]
done
