### ISSUE TITLE
text was not translated into pt-br

### ISSUE THREAD

**Issue by uziasferreirazup** [ZupIT/beagle-docs#450]
https://docs.usebeagle.io/v1.6/pt/tutorials/how-to-create-new-actions/

current:

Como criar novas actions
Como criar novas actions
Nesta seção, você confere como criar Actions Customizadas para serem usadas em eventos mas sendo tratadas pela aplicação frontend

what I think it could be in pt-br:

Como criar novas ações
Como criar novas ações
Nesta seção, você confere como criar Ações Customizadas para serem usadas em eventos mas sendo tratadas pela aplicação frontend

Current image:
<img width="941" alt="Screen Shot 2021-03-30 at 02 34 17" src="https://user-images.githubusercontent.com/63263091/112938681-74c49580-9100-11eb-96c7-5ba06d9a78ae.png">

**Comment by carlossteinzup** [comment]
Done
