### ISSUE TITLE
Corrigir imagens, links quebrados e tutoriais depreciados

### ISSUE THREAD

**Issue by luismaximozup** [ZupIT/beagle-docs#466]
Seria ideal revisarmos todos os tutoriais e verificar se estão condizentes e coesos com as respectivas versões.

- [x] **images:** 
    - https://docs.usebeagle.io/v1.5/get-started/installing-beagle/backend/
    - https://docs.usebeagle.io/v1.6/get-started/installing-beagle/backend/
- [x] **Live Preview Link:** 
    - https://docs.usebeagle.io/v1.5/resources/live-preview/ 
- [x]  **Deprecated tutorial**: 
    - https://docs.usebeagle.io/v1.5/get-started/installing-beagle/backend/

**Comment by carlossteinzup** [comment]
done
