### ISSUE TITLE
Sync examples of custom widgets documentation page for Android / IOS

### ISSUE THREAD

**Issue by hernandazevedozup** [ZupIT/beagle-docs#475]
The page for custom widgets on android have lots of examples:
https://docs.usebeagle.io/v1.6/resources/customization/beagle-for-android/custom-widget/simple-custom-widget/

- [x] android https://github.com/ZupIT/beagle-docs/pull/491

The custom widgets page for IOS is much more simpler than the android. Maybe we should make the same examples of android on IOS
https://docs.usebeagle.io/v1.6/resources/customization/beagle-for-ios/custom-widgets/

**Comment by carlossteinzup** [comment]
Um exemplo em iOS foi criado, mas diferente do exemplo Android.
O próximo passo é analisar as duas documentação mapeando o que falta implementar e atualizar

**Comment by carlossteinzup** [comment]
done
