### ISSUE TITLE
Try to figure out how to set up sourcery in separate files. Show how to do it. (@Adoption)

### ISSUE THREAD

**Issue by hernandazevedozup** [ZupIT/beagle-docs#476]
In the example today in beagle, the sourcery configuration creates a single file with the generated sources.
It would be nice if we have an example of how to configurer sourcery to generate separated files for each source.
https://docs.usebeagle.io/v1.6/resources/customization/beagle-for-ios/sourcery/

**Comment by carlossteinzup** [comment]
discontinued
