### ISSUE TITLE
Examples of beagle codes are with deprecated methods in the documentation

### ISSUE THREAD

**Issue by luisoliveirazup** [ZupIT/beagle-docs#526]
## Use case

Examples of beagle codes are with deprecated methods in the documentation, in the case applyStyle, applyFlex, unitReal () and unitPercent ()

![image](https://user-images.githubusercontent.com/59032818/117200822-4ce0e580-adc2-11eb-9ba4-88a992a5e2a7.png)

## Proposal

Change all example to new implementation

![image](https://user-images.githubusercontent.com/59032818/117201692-5159ce00-adc3-11eb-89f7-2040ce50a6f1.png)

**Comment by carlossteinzup** [comment]
addressed in another issue
