### ISSUE TITLE
AnalyticsProvider is outdate

### ISSUE THREAD

**Issue by viniciusguardieirozup** [ZupIT/beagle-docs#578]
## Description
The AnalyticsProvider example on page https://docs.usebeagle.io/v1.7/pt/resources/analytics/  is outdated.

## Expected Results
On Android, the getConfig method should be "override fun getConfig(): AnalyticsConfig" (without the nullable mark "?"), the same happens on iOS

**Comment by hectorcustodiozup** [comment]
Closed with https://github.com/ZupIT/beagle-docs/pull/830
