### ISSUE TITLE
Update the Docs footer License to Creative Commons

### ISSUE THREAD

**Issue by otaviojava** [ZupIT/beagle-docs#719]
Please, could you update the license footer to use Creative Commons instead?

https://creativecommons.org/licenses/by/4.0/

You can use this site as a reference:

https://creativecommons.org/choose/results-one?license_code=by&amp;jurisdiction=&amp;version=4.0&amp;lang=en

Simple sample of footer

```html
<p>&copy; 2021 Zup IT <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons</a> <a href="https://insights.zup.com.br/politica-privacidade">Privacy Policy</a></p>
```

Ps: In the English version, we need to check the English version of this policy: https://insights.zup.com.br/politica-privacidade

Docs website: https://docs.usebeagle.io/v1.9/

**Comment by carlossteinzup** [comment]
@otaviojava About this message "Ps: In the English version, we need to check the English version of this policy: https://insights.zup.com.br/politica-privacidade"

What english version? There is no link to english version on the link you have provided. Or do you mean that we have to create an english version and list that on our documentation web page?

**Comment by otaviojava** [comment]
@carlossteinzup it is because this link is in Portuguese.
There is no link to the translated page, so that we can move forward without it.

**Comment by carlossteinzup** [comment]
Done https://github.com/ZupIT/beagle-docs/pull/739
It is set in our pre-release to Beagle version 1.10 , we are updating the 1.9 version. 
http://docs-beta.usebeagle.io/overview/

**Comment by otaviojava** [comment]
Thank you
