### ISSUE TITLE
Traduzir o Github App para Github Actions (DCO / GPG)

### ISSUE THREAD

**Issue by carlossteinzup** [ZupIT/beagle-docs#764]
- [x] Finalizar lógica e testagem.
- [x] Traduzir o Github App para Github Actions (DCO / GPG)
- [x] Criar o repositório no github
- [x] Adicionar código no repositório oficial
- [x] Instalar validador em pelo menos dois projetos para validar a solução/colher feedbacks
- [ ] Publicar no marketplace

**Comment by carlossteinzup** [comment]
Estamos definindo se pode ser uma Action ao inves de um App

**Comment by hectorcustodiozup** [comment]
Até o momento a ação está sendo usada mas sem publicação no marketplace https://github.com/ZupIT/zup-dco-validator. Caso seja decidido seguir com a publicação outra issue será aberta no repositório da action.
