### ISSUE TITLE
Criar documentação para Context DSL EN e Revisar documentação em PT

### ISSUE THREAD

**Issue by carlossteinzup** [ZupIT/beagle-docs#781]
https://github.com/ZupIT/beagle-docs/pull/763
- [x] Revisar versão PT 
- [x] Criar versão EN

**Comment by jessica-tw** [comment]
Versão EN > PR > https://github.com/ZupIT/beagle-docs/pull/786

**Comment by carlossteinzup** [comment]
@jessica-tw = ninja demais
