### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by victorrabelozup** [ZupIT/beagle-docs#808]
Please provide all the information requested bellow. Issues that do not follow this format are likely to stall.

## Description :bookmark_tabs:
This part of the documentation is getting a 403 error in the exemple.
https://docs.usebeagle.io/v1.10/api/context/operations/how-to-register-a-new-operation/

## Expected Results :pray:
Should show the json exemple.

**Comment by hectorcustodiozup** [comment]
Hello @victorrabelozup,

Thanks for your help on warning us about this issue, this seems to be an error with our cloudfront and is currently under investigation. I will keep you informed on a solution.

**Comment by hectorcustodiozup** [comment]
Cloudfront configuration has been updated an the project can now be accessed again.
