### ISSUE TITLE
Beagle 2.0: work still needed

### ISSUE THREAD

**Issue by Tiagoperes** [ZupIT/beagle-docs#836]
The developers in the Orange team don't document the features in more than one language. So Beagle Open still needs to do the translation work regarding the modifications in this new version. 

### Translate entire file from portuguese:
- [x] `content/en/web/commons/beagle-remote-view.md`

### Translate entire file from english:
- [x] `content/pt/web/commons/navigation/navigation-controllers.md`
- [x] `content/pt/web/commons/view-client.md`
- [x] `content/pt/android/customization/view-client.md`
- [x] `content/pt/ios/customization/dependencies/_index.md`
- [x] `content/pt/ios/customization/dependencies/log-system.md`
- [x] `content/pt/ios/customization/dependencies/overview.md`
- [x] `content/pt/ios/customization/dependencies/view-client.md`
- [x] all files under `content/pt/flutter`

### Replicate the changes made to the following portuguese files in the respective english version:
**For the files below, I advise checking the changes at the diff for [this PR](https://github.com/ZupIT/beagle-docs/pull/837/files).**
- [x] `content/pt/web/angular/using-beagle.md`
- [x] `content/pt/web/commons/advanced-topics/rendering.md`
- [x] `content/pt/web/commons/advanced-topics/the-beagle-view.md`
- [x] `content/pt/web/react/using-beagle.md`
- [x] `content/pt/api/actions/navigate/navigationcontext.md`
- [x] `content/pt/api/actions/navigate/popstack.md`
- [x] `content/pt/api/actions/navigate/poptoview.md`
- [x] `content/pt/api/actions/navigate/popview.md`
- [x] `content/pt/api/actions/navigate/pushstack.md`
- [x] `content/pt/api/actions/navigate/pushview.md`
- [x] `content/pt/api/actions/navigate/resetapplication.md`
- [x] `content/pt/api/actions/navigate/resetstack.md`
- [x] `content/pt/api/components/widget.md`
- [x] `content/pt/api/context/operations/arrays-manipulation-operator.md`
- [x] `content/pt/api/context/operations/comparison-operator.md`
- [x] `content/pt/api/context/operations/logic-operator.md`
- [x] `content/pt/api/context/operations/other-operators.md`
- [x] `content/pt/api/context/operations/string-manipulation-operator.md`
- [x] `content/pt/api/style/_index.md`
- [x] `content/pt/api/style/corner-radius.md`
- [x] `content/pt/api/style/edge-value.md`
- [x] `content/pt/api/style/overview.md`
- [x] `content/pt/api/style/size.md`
- [x] `content/pt/api/style/unit-value.md`
- [x] `content/pt/resources/components-positioning/basis.md`
- [x] `content/pt/resources/components-positioning/grow.md`
- [x] `content/pt/resources/components-positioning/overview.md`
- [x] `content/pt/resources/components-positioning/padding.md`
- [x] `content/pt/resources/components/composed-component.md`
- [x] `content/pt/resources/dsl-operations/arrays-manipulation-operator.md`
- [x] `content/pt/resources/dsl-operations/comparison-operator.md`
- [x] `content/pt/resources/dsl-operations/logic-operator.md`
- [x] `content/pt/resources/dsl-operations/other-operators.md`
- [x] `content/pt/resources/dsl-operations/string-manipulation-operator.md`
- [x] `content/pt/android/tutorials/test/benchmark-beagle-movies.md`
- [x] `content/pt/api/context/global-context.md`
- [x] `content/pt/backend/get-started/installing-beagle.md`
- [x] `content/pt/ios/customization/custom-actions/_index.md`
- [x] `content/pt/ios/customization/custom-beagle-navigation-controller.md`
- [x] `content/pt/ios/customization/dependencies/deeplink-handler.md`
- [x] `content/pt/ios/customization/dependencies/imagedownloader.md`
- [x] `content/pt/ios/customization/dependencies/network-layer.md`
- [x] `content/pt/ios/customization/loading-and-error-treatment.md`
- [x] `content/pt/ios/customization/navigation-animation.md`
- [x] `content/pt/ios/getting-started.md`
- [x] `content/pt/ios/libs/beagle-grpc-ios.md`
- [x] `content/pt/ios/libs/beagle-scaffold.md`
- [x] `content/pt/ios/tutorials/test/benchmark-beagle-movies.md`
- [x] `content/pt/web/commons/advanced-topics/data-structure.md`
- [x] `content/pt/web/commons/advanced-topics/rendering.md`
- [x] `content/pt/web/commons/advanced-topics/the-beagle-view.md`
- [x] `content/pt/web/commons/beagle-service-parameter.md`
- [x] `content/pt/web/commons/remote-view-parameters.md`
- [x] `content/pt/web/commons/standard-headers.md`
- [x] `content/pt/ios/customization/imagedownloader.md`
- [x] `content/pt/ios/customization/network-layer.md`
- [x] `content/pt/ios/customization/custom-actions/_index.md`
- [x] `content/pt/ios/customization/custom-actions/async-custom-action.md`
- [x] `content/pt/ios/customization/custom-actions/custom-action.md`
- [x] `content/pt/ios/customization/custom-widget/custom-widget.md`

### Remove the equivalent file in the english version:
- [x] `content/pt/api/style.md`
- [x] `content/pt/ios/customization/beagles-dependencies.md`
- [x] `content/pt/ios/customization/gerenciar-cache.md`
- [x] `content/pt/ios/customization/log-system.md`
- [x] `content/pt/ios/customization/sourcery.md`
- [x] `content/pt/resources/cache/_index.md`
- [x] `content/pt/resources/cache/how-to-configure-cache.md`
- [x] `content/pt/resources/cache/overview.md`
- [x] `content/pt/web/commons/cache-strategy.md`
- [x] `content/pt/ios/customization/custom-widget/serverdrivencomponent-custom-widget.md`
- [x] `content/pt/ios/customization/gerenciar-cache.md`
- [x] `content/pt/ios/customization/sourcery.md`

**Comment by carlossteinzup** [comment]
done
